### ISSUE TITLE
BUG: Draft component bus type mirrors assigned incorrectly

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#101]
## Description:

Creating draft component in HW diagram and adding draft bus to that enables mirrioring existing bus being created on component bus list when finalizing draft component. Bus definitions are inferred correctly, but mode is incorrectly drawn from IPXACT14 standard modes. 

E.G. Conneccting initiator port to draft interface creates it to be mirrored master, instead of target. After this context menu correctly offers only 22 standard types as options for the mode.

## Kactus2 Version:

3.13

## Platform:

win10

## IPXACT Standard:

2022

**Comment by hagantsa** [comment]
Fixed in 03658b47cffb07003a8313b4b544ac74efd210f0.
