### ISSUE TITLE
Bug: Crash on manual port editor cancellation

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#102]
## Description

When creating draft IO in HW diagram, connecting it with local defined port, Kactus2 offers to either complete connection to bus with automatically copying ports, or manually setting them up with dedicated interface. Selecting manual interface it opens tool window to do this. When it is cancelled, it causes tool to crash.

## Kactus2 Version:

3.13

## OS

win10

## IPXACT Standard

2022

**Comment by hagantsa** [comment]
Fixed in dc1169e43201174db2908a308245c408b59fbd0e.
