### ISSUE TITLE
Bug: Mirrored interface of 22 standard in HW diagram editor shows wrong colour

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#104]
## Description

When creating mirrored Initiator and target interfaces, bus icon colours get inferred to be all of the same type (for mirrored target). Behavior seems to be correct, so issue is likely only visual. Additionally, context help for bus interface shows old interface names in image.

## Kactus2 Version

3.13

## OS

win10

## IPXACT Standard

2022

**Comment by teuhom** [comment]
Fixed in 07518c5261f3106fa8baefd47d25f65d2ef91513
