### ISSUE TITLE
Bug: bus definition wire presence displays wrong value in bus interface port map editor

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#106]
## Description

Required wires in bus definitions are displayed as optional in bus interface port editor. Additionally, option to add only ports for either optional or required ports does not add any ports. Option to add all ports does add all interface ports.

## Kactus2 Version

3.13

## Os

win10

## IPXACT Standard

2022

**Comment by hagantsa** [comment]
Fixed in ef11f9405509d21d6123f087f82004fbbcafc9cd
