### ISSUE TITLE
Issue with port width evaluation formula with parenthesis 

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#108]
## Category

Bug

## Description: 

When adding port width with parenthesis, the formula evaluation breaks. First parenthesis is lost and terms are added in incorrect order, parameters are also lost. This applies only for first filling of field.

for example (3-1)-1 evaluates to -1)3-1, while 3-1-1 evaluates correctly.

Though tool is fine when you first enter the formula without parenthesis, then enter, then edit to add only the parenthesis.

It would seem it might be some kind of initialization issue, as I repeated testing to a field enough times, it started to evaluate results correctly every time.

## Kactus2 version 

3.13.1

## OS

Win10

## IPXACT standard

2022

**Comment by hagantsa** [comment]
Should now be fixed in 8fd2ee30c5dd545ef5ece5077cccb49ec3a121cb.
