### ISSUE TITLE
HW designer design parameter menu does not appear

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#113]
## description

In hardware designer, design parameter menu is set as visible by default when opening a diagram. Despite this it does not appear on screen (by default on the bottom edge below design). In menu it is ticked as being active and visible. To get it to appear on screen, one must disable the tick mark and re-tick it to get it appear on screen. 

Once it is visible, it works correctly.

Changing tabs hides it again, and it must be unticked and ticked to get it appear again.

## kactus2 Version

3.13.2 / 64bit

## Os

win10

## ipxact standard

2022

**Comment by hagantsa** [comment]
This should be fixed in 255be9dd3a99ef37b4b2e2b94c8302669343b1a3.
