### ISSUE TITLE
ipxactexamplelib Validation failing with git main build

### ISSUE THREAD

**Issue by AmeyaVS** [kactus2/kactus2dev#115]
I upgraded my build of the kactus2 from source with latest branch: main '[8db0d32](https://github.com/kactus2/kactus2dev/commit/8db0d32c51fae7fa5f879de4a3fd9aad787b3a60)'

I am observing following validation failing in the ipxactexamplelib repository: https://github.com/kactus2/ipxactexamplelib

![image](https://github.com/user-attachments/assets/e566d6b5-2d9f-4946-b4fe-71d4c3f56788)

**Comment by hagantsa** [comment]
Thank you for reporting! The example library is now updated and should be error free with the latest Kactus2 build(s).
