### ISSUE TITLE
qt6-documentation-tools is a dependency

### ISSUE THREAD

**Issue by krabo0om** [kactus2/kactus2dev#117]
The above mentioned Ubuntu package provides `qhelpgenerator` and has to be installed to run `createhelp`. The [list in the wiki](https://github.com/kactus2/kactus2dev/wiki/Building-Kactus2-from-source#21-install-qt6) has to be extended.

**Comment by hagantsa** [comment]
Hi,

Thank you for reporting this. The dependency list has now been updated.
