### ISSUE TITLE
memoryMaps visualizer slows down on large models

### ISSUE THREAD

**Issue by DanChianucci** [kactus2/kactus2dev#15]
If a model with a very large memoryMap is loaded, it can take up to 10 mins just to display the main display tab.  When clicking between registers there is also a significant delay between the click and when the form is actually displayed.

I ran some basic profiling and saw that the majority of the CPU cycles are taken up be the visualizer on the right hand side trying to refresh.  If you shrink said visualizer until it disappears, the GUI becomes much more responsive.

The only models that I have used large enough to cause this issue contain nested register files, so I'm not sure if the root cause is just the number of visualization elements, or if it has something to do with how changes propagate through the registerFile.

**Comment by epekkar** [comment]
Hi Dan,

We made some improvements on the visualization performance in d3ed98d5f9a1ff186fad832fe109f17b09a904b9. The change is most notable for registers with dimensions, but other memory maps should now run faster as well. Let me know, if it fixed the issue with your component with large memory map(s).

**Comment by DanChianucci** [comment]
It looks like it has sped up the amount of time it takes to initially open the view, but I still need to remove that view in order for the gui to be responsive to moving through the registers/fields.

**Comment by epekkar** [comment]
Hi Dan,
I changed the update logic for the visualization in 3c0d3600d1124333e7af0cd6a08bf35239bce2ae and the responsiveness should be now much better. The changes are already merged in the master branch. Please let us know, if the issue persists.
