### ISSUE TITLE
Wrong Exec name in .desktop file.

### ISSUE THREAD

**Issue by m-kru** [kactus2/kactus2dev#22]
I have just built current master on arch and installed. I have realized that in .desktop file, that is copied to `/usr/share/applications/kactus2.desktop`, there is a minor error.
Namely:
```
TryExec=Kactus2                                                                           
Exec=Kactus2
```
Lower case 'k' should be used.

**EDIT**
I have prepared pull request.

**Comment by epekkar** [comment]
Fixed in 7f983d0c415a9630b0c4708037b4013e24d7cc98
