### ISSUE TITLE
Build on CentOS 7 fails

### ISSUE THREAD

**Issue by luudee** [kactus2/kactus2dev#26]
./configure completes fine

make ends with:

.....

g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DIPXACTMODELS_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -IGeneratedFiles -I. -I./GeneratedFiles/Release -I.. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -IGeneratedFiles/release -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o release/XmlUtils.o utilities/XmlUtils.cpp
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DIPXACTMODELS_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -IGeneratedFiles -I. -I./GeneratedFiles/Release -I.. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -IGeneratedFiles/release -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o release/BusDefinitionUtils.o utilities/BusDefinitionUtils.cpp
utilities/BusDefinitionUtils.cpp: In function ‘QStringList BusDefinitionUtils::getSystemGroups(QSharedPointer<const BusDefinition>, LibraryInterface*)’:
utilities/BusDefinitionUtils.cpp:26:40: error: invalid initialization of non-const reference of type ‘VLNV&’ from an rvalue of type ‘VLNV’
     VLNV& extendVLNV = bus->getExtends();
                                        ^
In file included from ../IPXACTmodels/common/Document.h:20:0,
                 from ../IPXACTmodels/BusDefinition/BusDefinition.h:17,
                 from utilities/BusDefinitionUtils.cpp:14:
../IPXACTmodels/common/VLNV.h: In instantiation of ‘static void* QtMetaTypePrivate::QMetaTypeFunctionHelper<T, Accepted>::Construct(void*, const void*) [with T = VLNV; bool Accepted = true]’:
/usr/include/qt5/QtCore/qmetatype.h:1687:76:   required from ‘int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = VLNV; typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType = QtPrivate::MetaTypeDefinedHelper<VLNV, true>::DefinedType]’
/usr/include/qt5/QtCore/qmetatype.h:1712:77:   required from ‘int qRegisterMetaType(const char*, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = VLNV; typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType = QtPrivate::MetaTypeDefinedHelper<VLNV, true>::DefinedType]’
../IPXACTmodels/common/VLNV.h:263:1:   required from here
../IPXACTmodels/common/VLNV.h:88:2: warning: unused parameter ‘other’ [-Wunused-parameter]
  VLNV(VLNV const& other) = default;
  ^
In file included from /usr/include/qt5/QtCore/qobject.h:54:0,
                 from /usr/include/qt5/QtCore/qsharedpointer_impl.h:64,
                 from /usr/include/qt5/QtCore/qsharedpointer.h:48,
                 from /usr/include/qt5/QtCore/QSharedPointer:1,
                 from ../IPXACTmodels/ipxactmodels_global.h:4,
                 from utilities/BusDefinitionUtils.h:15,
                 from utilities/BusDefinitionUtils.cpp:12:
/usr/include/qt5/QtCore/qmetatype.h:765:59: note: synthesized method ‘VLNV::VLNV(const VLNV&)’ first required here
             return new (where) T(*static_cast<const T*>(t));
                                                           ^
make[1]: *** [release/BusDefinitionUtils.o] Error 1
make[1]: Leaving directory `/share/cac/kactus2dev-master/IPXACTmodels'
make: *** [sub-IPXACTmodels-IPXACTmodels-pro-make_first-ordered] Error 2

**Comment by epekkar** [comment]
Hi ludee,

Thank you for reporting the issue. I got it fixed in a5a9e3e705d7e94f978110683d74a8149173a19a.
