### ISSUE TITLE
Field Visualization Missing and Resize Crash

### ISSUE THREAD

**Issue by jm4rtin** [kactus2/kactus2dev#27]
After changing 0x0 => 'h0 (and so forth) from the IP-XACT 1685-2014 specification component example (which seems to violate the specification but would still be nice if it worked) I tried to load just part of a single memory map into cactus. What I ended up with is this:
![image](https://user-images.githubusercontent.com/20426677/57105680-a6e8d500-6ce8-11e9-8f9c-42d640077f18.png)

It only shows F1 but not the other 3 bit fields (F2-F4) in the visualization. Also, with the map expanded as shown, if I resize the visualization to be wider it crashes.

Example XML: [test.txt](https://github.com/kactus2/kactus2dev/files/3139896/test.txt)

**Comment by epekkar** [comment]
Hi jm4rtin,

Thank you for reporting this error in the visualization. There was a bug in creating the field layout which made all the elements overlap and caused the crash when resizing. 

The issue was fixed in 9a128c10ef117c74cbe609b179e86269afea99f2.
