### ISSUE TITLE
Component tags

### ISSUE THREAD

**Issue by epekkar** [kactus2/kactus2dev#28]
Add feature to add tags to components for categorization:
- [x] View and edit in Component Editor general-section
- [x] Use as filters to library view

**Comment by teuhom** [comment]
Created tag editor in bd80d0b2442ccf11290f97b5166d9d4840ff520f

**Comment by teuhom** [comment]
Added completer to tag editor in 08f2897add507638029ab44a364abc5b303f24f2

**Comment by teuhom** [comment]
Added tag filters to library 96a1b787dacb1c47fd969dcd771fa8fbc5d3c3d4
