### ISSUE TITLE
Moving big instances in HW-Design makes Kactus2 crash.

### ISSUE THREAD

**Issue by VoigtSebastian** [kactus2/kactus2dev#30]
I tried moving 2 bigger instances in the HW-Desigin and Kactus2 crashed every time, so I tried some combinations and it turns out moving an instance with 15 or more Ad-hoc ports makes Kactus2 crash on my system.
I am using a Windows PC and did not have any other issues with the software crashing or misbehaving.

**Comment by teuhom** [comment]
Fixed in 6b8ffcca4c4d70353c9a33bab9e8a94205cdf427.
