### ISSUE TITLE
new release tag request: v3.8.0 is far behind the master branch.

### ISSUE THREAD

**Issue by vowstar** [kactus2/kactus2dev#38]
The latest release tag is https://github.com/kactus2/kactus2dev/releases/tag/v3.8.0, and it is far behind the master branch.
This may brings problems to many Linux distributions that want to use the latest version of the package. Could an updated release tag be issued if it is convenient? Thank you!

**Comment by epekkar** [comment]
Hi vowstar,
There will be a new release soon.

**Comment by ithinuel** [comment]
Any update on plans for the new release? :)

**Comment by epekkar** [comment]
New release will be available latest at the end of June. Sorry for the unexpected delay.

**Comment by epekkar** [comment]
Version 3.9.0 is now released.
