### ISSUE TITLE
Build and install errors in 3.9.0

### ISSUE THREAD

**Issue by maloo** [kactus2/kactus2dev#44]
1) The configure script is not adding - lpython3.8 to the LDFLAGS. This can be done by adding --embed to python3-config, but I could not find where it was called so had to manually edit the makefile after configure.
2) The install script doesn't install libIPXACTmodels.so.1 so I had to create the softlink myself and copy the binary from builddir/executable/

I did the build on Ubuntu 20.04 in WSL2. After the above fixes I could start it in WSL2.

**Comment by epekkar** [comment]
The configuration is now fixed and should work with Python 3.8+.
