### ISSUE TITLE
Deleting bus definition wire ports breaks components.

### ISSUE THREAD

**Issue by TonyReinberger** [kactus2/kactus2dev#59]
Kactus2 3.9.171 64bit Windows

I've created a bus definition and defined a few wired ports.

![image](https://user-images.githubusercontent.com/28468090/159585053-56186baa-17d7-4726-b3b9-460cb085416b.png)

I then have a component which maps them on a bus interface.

![image](https://user-images.githubusercontent.com/28468090/159585175-66a6b335-4236-4e48-a2b1-3ce87e83a89d.png)

If I then delete a bus wired port (in this case port_1) and go back to the component, selecting the portmap, the table is now broken with an empty line.

![image](https://user-images.githubusercontent.com/28468090/159587428-d16ec8d5-db7d-4ccd-8b14-537283f5f750.png)

Changing the sort order will even mess with the headings.

![image](https://user-images.githubusercontent.com/28468090/159587510-dc501f4d-9511-41c5-b6c2-09cf1fbd0ac6.png)

An attempt to save the component results in the following error.

> The document contained the following error(s):
> * Could not locate logical port port_1 mapped within master bus interface bus_interface

The only way to fix the component is to go into the xml file and delete the portmap for port_1. Once this is done, the bus interface is restored without errors.

![image](https://user-images.githubusercontent.com/28468090/159588092-2caa6a31-e4fb-4f69-bdbc-9ef8a5bd51fe.png)

**Comment by teuhom** [comment]
Fixed in https://github.com/kactus2/kactus2dev/commit/62c64873baa98efc6fed89ce1b953c0eea6d732a
