### ISSUE TITLE
new release tag request: v3.9.333 is missing

### ISSUE THREAD

**Issue by vowstar** [kactus2/kactus2dev#62]
The latest release tag is https://github.com/kactus2/kactus2dev/releases/tag/v3.9.0, and it is far behind the master branch.
This may brings problems to many Linux distributions that want to use the latest version of the package. Could an updated release tag be issued if it is convenient? Thank you!

**Comment by epekkar** [comment]
Hi vowstar,

We are working on a couple of enhancements before the next release, but there will be one soon.

**Comment by epekkar** [comment]
Version 3.10 is now released
