### ISSUE TITLE
kactus2 needs at least python3.8

### ISSUE THREAD

**Issue by mkettn** [kactus2/kactus2dev#65]
I*ve got an error when compiling kactus2 with python3.7, that it cannot find Python.h although I've installed it. The reason is, that - at least on my distribution, Ubuntu 18.04 - python3.7-config doesn't know the `--embed` command line argument. It will just print the usage. please update the readme file accordingly.

**Comment by ktbarrett** [comment]
The README states for the current release that Python 3.10 is the minimum supported version of Python.

**Comment by mkettn** [comment]
yes, you where right. I think I checked out out a release tag, where it wasn't mentioned in the readme.

**Comment by epekkar** [comment]
The current compilation should work with 3.8 and newer. We tested the build with 3.10, that works for sure.
