### ISSUE TITLE
 libIPXACTmodels.so.1 

### ISSUE THREAD

**Issue by Paul-Chaffey** [kactus2/kactus2dev#71]
Hi,

I have built kactus2 on ubuntu 22.10 and everything seems clean. When I start kactus2 on the command line, I see the following:

kactus2: error while loading shared libraries: libIPXACTmodels.so.1: cannot open shared object file: No such file or directory

What am I missing exactly ?

Thx Paul.

**Comment by epekkar** [comment]
Hi Paul,

You are missing the shared library or, more exactly, where to load it. The most straightforward way to fix this is to provide the library location as you are starting Kactus2. Your command to run Kactus2 should look something like `LD_LIBRARY_PATH=<path to kactus2>/executable kactus2`. You can also cd to the executable directory and simply run `LD_LIBRARY_PATH=. ./kactus2` as shown in [section 3a](https://github.com/kactus2/kactus2dev#3a-run-kactus2-gui) in readme.
