### ISSUE TITLE
Context Menu Options: "Open Containing Folder" and "Open XML File" Does not work on Linux

### ISSUE THREAD

**Issue by AmeyaVS** [kactus2/kactus2dev#80]
It seems the context menu options on an IP-XACT Instance does not work on Linux Builds:

- Open Containing Folder
- Open XML File

Does Qt need support from the environment to launch a file manager window, default system text editor.

**Comment by teuhom** [comment]
I tried replicating this on my Ubuntu 22.04 and it seems to be working fine.
What version of Kactus2 are you using?

**Comment by AmeyaVS** [comment]
I am building it on Fedora 38 with the master branch.
Let me get back to you with the git revision.

**Comment by AmeyaVS** [comment]
Could not reproduce the issue with the changes in the main branch.
Built using the commit id: d728e7d1bdeecb8e519ffe2e6395cfc167823435
