### ISSUE TITLE
Missing Fields in Memory Maps Visualization

### ISSUE THREAD

**Issue by pascal-creonic** [kactus2/kactus2dev#83]
In some cases fields are not showing in the memory maps visualization.
What I have found:
1. If only a single field is present, it is not showing up, no matter what.
1. If two fields are present, which do not occupy the full register, they are showing up
1. If two fields are present, which do occupy the full register, they are not showing up. However, for more than two fields occupying the full register, they are showing up
1. If one of two fields' isPresent value is set to false, no fields are shown. However, if more than two fields are defined of which only one is present, it is showing up

[demo.1.txt](https://github.com/kactus2/kactus2dev/files/12416701/demo.1.txt) contains the minimal example producing the memory maps visualization shown below.
![missing_fields](https://github.com/kactus2/kactus2dev/assets/142967748/b5f8d19b-ec04-4b3c-aea3-40776959be60)

Version: kactus2 3.12 built on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-75-generic x86_64) from the release tar-package

**Comment by epekkar** [comment]
Thanks for reporting this one. We will investigate it in more depth, but so far we found out that the visualization only fails on Linux.

**Comment by hagantsa** [comment]
Fixed in 43096fd1e837ac30bafcb622438551ae337afa37.
