### ISSUE TITLE
Qhelgenerator and Qmake not found

### ISSUE THREAD

**Issue by Ryuji-Yatahagane** [kactus2/kactus2dev#91]
So after the step 1 completed execute the ./configure command and the system said:

" Qhelgenerator not found. Please set the variable QTBIN_PATH to Qt binary files. "
" Qmake not found. Please set the variable QTBIN_PATH to Qt binary files. "

I already hace done this, my files are on /lib/qt6/bin  and the variable on configure file is QTBIN_PATH=/lib/qt6/bin

Is there other path's where i sould check ?

![image](https://github.com/kactus2/kactus2dev/assets/152328621/3b405acd-f42e-49a4-80cb-2bcdcacac77c)

**Comment by epekkar** [comment]
Fixed in #84

**Comment by Ryuji-Yatahagane** [comment]
It works, thanks u
