### ISSUE TITLE
Supporting alternate register

### ISSUE THREAD

**Issue by DenizzzGuzell** [kactus2/kactus2dev#93]
Hi, I could not find any option to design memory using alternate registers such as uart receiver address 0 read only and uart transmitter register address 0 write only. It throws error as ` Registers rcv_buf and tr_buf overlap within address block UART`. Does Kactus2 supports alternate register description?

**Comment by epekkar** [comment]
Hi Deniz,

Currently Kactus2 does not support alternate registers.

**Comment by DenizzzGuzell** [comment]
Hi epekkar,

Do you have any plan to add alternate registers to Kactus2 because of high necessity and usage of alternate registers.

**Comment by hagantsa** [comment]
Hi Deniz,

Alternate registers are something we probably will want to add to Kactus2, but there is currently no timeline set for it.

**Comment by DenizzzGuzell** [comment]
Hello, 

Thank you for answer.
