### ISSUE TITLE
Running Kactus2 on CentOS 7

### ISSUE THREAD

**Issue by abdullahyildiz** [kactus2/kactus2dev#96]
Since the latest version of Kactus2 requires Qt6 and the newer versions of Qt are not maintained in CentOS 7 package repositories, I can also suggest running Kactus2 in a Docker container on CentOS 7.

For this, just create a [Ubuntu Docker image](https://hub.docker.com/_/ubuntu) on your CentOS 7 host machine and build Kactus2 in the Docker image itself. _For those who are not very experienced with Docker: do not forget to save your changes via [docker commit](https://docs.docker.com/engine/reference/commandline/commit/) otherwise you may have to repeat the same installation steps._

```bash
# before starting Kactus2 in your Docker container, run the following command to enable applications running in the Docker container to use GUI of CentOS 7:
<centos> xhost +
# start the Docker container - assuming the image name is ubuntu:kactus2
<centos> docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix ubuntu:kactus2
```

Now the Docker container should be up and running:
```bash
# type kactus2 in your terminal:
<ubuntu> kactus2
```

Please note that the following workaround (which is explained [here](https://forum.qt.io/topic/136058/libqt6core-so-6-cannot-open-shared-object-file-even-though-it-exists-seems-to-depend-on-docker-host-os/3)) should be applied if the Docker host is CentOS 7 and if you receive the error `"libQt6Core.so.6: cannot open shared object file" received` when starting Kactus2:

```bash
# run the following command in your Docker container to resolve the issue:
<ubuntu> strip --remove-section=.note.ABI-tag libQt6Core.so.6
# type kactus2 in your terminal:
<ubuntu> kactus2
```

Note: The solution has been tested to run [Kactus2 Release for version 3.13.0](https://github.com/kactus2/kactus2dev/tree/v3.13.0).

**Comment by hagantsa** [comment]
Hi,

Thank you for sharing! I'll link this in our wiki page for others to find.
