### ISSUE TITLE
make first execution Error 

### ISSUE THREAD

**Issue by Ryuji-Yatahagane** [kactus2/kactus2dev#97]
![Captura de pantalla 2024-01-12 102121](https://github.com/kactus2/kactus2dev/assets/152328621/e9b3efff-3b89-4457-a726-268cc61178f4)

Hello everyone, 
I´m trying to compile and i got this error at the firs $make command.

It´s a known error ? 

Greatings,

**Comment by hagantsa** [comment]
Hi,

This error is most likely caused by an invalid `PYTHON_CONFIG` variable in `.qmake.conf`. The `PYTHON_CONFIG` variable should match the installed Python version. For example, for Python 3.11 it should be set to `python3.11-config`. Please make sure to follow the build instructions closely.

**Comment by Ryuji-Yatahagane** [comment]
Hello,
Thanks u so much for ur suggestion 
solves the problem.
