### ISSUE TITLE
Missing feature: Port wire editor / create ports from interface

### ISSUE THREAD

**Issue by Kyrhe** [kactus2/kactus2dev#99]
## Description:

Port wire editor has the capability to add ports from interfaces. This is currently missing from IPXACT 2022 standard components.

## Kactus2 version:

3.13

## Platform:

Win10

## IPXACT Standard

2022

**Comment by teuhom** [comment]
This should be fixed in 624d0426e77642bb3ec11f9ec344968b34e63454
